# Generated by Django 5.2.8 on 2025-11-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_remove_flashcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='pinyin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='translation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
