# Generated by Django 5.2.8 on 2025-12-03 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAChineseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('chinese_name', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(choices=[(1, 'HSK1'), (2, 'HSK2'), (3, 'HSK3'), (4, 'HSK4'), (5, 'HSK5'), (6, 'HSK6')], default=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('daily_xp', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('daily_goal', models.IntegerField(default=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.IntegerField(choices=[(1, 'light'), (2, 'dark')], default=1)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
