# Generated by Django 5.2.8 on 2025-12-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachineseuser',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
