# Generated by Django 5.2.8 on 2026-01-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cachineseuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachineseuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cachineseuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
