# Generated by Django 5.2.8 on 2026-01-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cachineseuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachineseuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
