# Generated by Django 5.2.8 on 2025-11-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSKWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(max_length=50)),
                ('pinyin', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=200)),
                ('level', models.IntegerField(choices=[(1, 'HSK 1'), (2, 'HSK 2'), (3, 'HSK 3'), (4, 'HSK 4'), (5, 'HSK 5'), (6, 'HSK 6')])),
                ('example_cn', models.CharField(blank=True, max_length=255, null=True)),
                ('example_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
